version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metro_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - metro_network

  nginx:
    image: nginx:alpine
    container_name: metro_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - metro_network

  db:
    image: mysql:8.0
    container_name: metro_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - metro_network

networks:
  metro_network:
    driver: bridge

volumes:
  dbdata: